package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1



/**
 * Autobus generated by hbm2java
 */
public class Autobus  implements java.io.Serializable {


     private Integer idAutobus;
     private String nombreAutobus;
     private int numeroPlazasLimite;

    public Autobus() {
    }

    public Autobus(String nombreAutobus, int numeroPlazasLimite) {
       this.nombreAutobus = nombreAutobus;
       this.numeroPlazasLimite = numeroPlazasLimite;
    }
   
    public Integer getIdAutobus() {
        return this.idAutobus;
    }
    
    public void setIdAutobus(Integer idAutobus) {
        this.idAutobus = idAutobus;
    }
    public String getNombreAutobus() {
        return this.nombreAutobus;
    }
    
    public void setNombreAutobus(String nombreAutobus) {
        this.nombreAutobus = nombreAutobus;
    }
    public int getNumeroPlazasLimite() {
        return this.numeroPlazasLimite;
    }
    
    public void setNumeroPlazasLimite(int numeroPlazasLimite) {
        this.numeroPlazasLimite = numeroPlazasLimite;
    }




}


