package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nifCliente;
     private String nombreCliente;
     private String apellidosCliente;
     private String password;
     private String correoCliente;
     private String telefonoCliente;
     private String domicilioCliente;
     private Set tarjetas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nifCliente, String nombreCliente, String apellidosCliente, String password, String correoCliente, String telefonoCliente, String domicilioCliente) {
        this.nifCliente = nifCliente;
        this.nombreCliente = nombreCliente;
        this.apellidosCliente = apellidosCliente;
        this.password = password;
        this.correoCliente = correoCliente;
        this.telefonoCliente = telefonoCliente;
        this.domicilioCliente = domicilioCliente;
    }
    public Cliente(String nifCliente, String nombreCliente, String apellidosCliente, String password, String correoCliente, String telefonoCliente, String domicilioCliente, Set tarjetas) {
       this.nifCliente = nifCliente;
       this.nombreCliente = nombreCliente;
       this.apellidosCliente = apellidosCliente;
       this.password = password;
       this.correoCliente = correoCliente;
       this.telefonoCliente = telefonoCliente;
       this.domicilioCliente = domicilioCliente;
       this.tarjetas = tarjetas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNifCliente() {
        return this.nifCliente;
    }
    
    public void setNifCliente(String nifCliente) {
        this.nifCliente = nifCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidosCliente() {
        return this.apellidosCliente;
    }
    
    public void setApellidosCliente(String apellidosCliente) {
        this.apellidosCliente = apellidosCliente;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreoCliente() {
        return this.correoCliente;
    }
    
    public void setCorreoCliente(String correoCliente) {
        this.correoCliente = correoCliente;
    }
    public String getTelefonoCliente() {
        return this.telefonoCliente;
    }
    
    public void setTelefonoCliente(String telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }
    public String getDomicilioCliente() {
        return this.domicilioCliente;
    }
    
    public void setDomicilioCliente(String domicilioCliente) {
        this.domicilioCliente = domicilioCliente;
    }
    public Set getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set tarjetas) {
        this.tarjetas = tarjetas;
    }




}


