package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Tarjeta tarjeta;
     private Viaje viaje;
     private String localizadorCompra;
     private Date fechaCompra;
     private double importeCompra;
     private Set ocupacions = new HashSet(0);

    public Compra() {
    }

	
    public Compra(Tarjeta tarjeta, Viaje viaje, String localizadorCompra, Date fechaCompra, double importeCompra) {
        this.tarjeta = tarjeta;
        this.viaje = viaje;
        this.localizadorCompra = localizadorCompra;
        this.fechaCompra = fechaCompra;
        this.importeCompra = importeCompra;
    }
    public Compra(Tarjeta tarjeta, Viaje viaje, String localizadorCompra, Date fechaCompra, double importeCompra, Set ocupacions) {
       this.tarjeta = tarjeta;
       this.viaje = viaje;
       this.localizadorCompra = localizadorCompra;
       this.fechaCompra = fechaCompra;
       this.importeCompra = importeCompra;
       this.ocupacions = ocupacions;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public String getLocalizadorCompra() {
        return this.localizadorCompra;
    }
    
    public void setLocalizadorCompra(String localizadorCompra) {
        this.localizadorCompra = localizadorCompra;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public double getImporteCompra() {
        return this.importeCompra;
    }
    
    public void setImporteCompra(double importeCompra) {
        this.importeCompra = importeCompra;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }




}


