package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprabackup generated by hbm2java
 */
public class Comprabackup  implements java.io.Serializable {


     private Integer idCompraBackup;
     private Tarjeta tarjeta;
     private Viajebackup viajebackup;
     private String localizadorCompraBackup;
     private Date fechaCompraBackup;
     private double importeCompraBackup;
     private Date fechaBajaCompraBackup;
     private Set ocupacionbackups = new HashSet(0);

    public Comprabackup() {
    }

	
    public Comprabackup(Tarjeta tarjeta, Viajebackup viajebackup, String localizadorCompraBackup, Date fechaCompraBackup, double importeCompraBackup, Date fechaBajaCompraBackup) {
        this.tarjeta = tarjeta;
        this.viajebackup = viajebackup;
        this.localizadorCompraBackup = localizadorCompraBackup;
        this.fechaCompraBackup = fechaCompraBackup;
        this.importeCompraBackup = importeCompraBackup;
        this.fechaBajaCompraBackup = fechaBajaCompraBackup;
    }
    public Comprabackup(Tarjeta tarjeta, Viajebackup viajebackup, String localizadorCompraBackup, Date fechaCompraBackup, double importeCompraBackup, Date fechaBajaCompraBackup, Set ocupacionbackups) {
       this.tarjeta = tarjeta;
       this.viajebackup = viajebackup;
       this.localizadorCompraBackup = localizadorCompraBackup;
       this.fechaCompraBackup = fechaCompraBackup;
       this.importeCompraBackup = importeCompraBackup;
       this.fechaBajaCompraBackup = fechaBajaCompraBackup;
       this.ocupacionbackups = ocupacionbackups;
    }
   
    public Integer getIdCompraBackup() {
        return this.idCompraBackup;
    }
    
    public void setIdCompraBackup(Integer idCompraBackup) {
        this.idCompraBackup = idCompraBackup;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Viajebackup getViajebackup() {
        return this.viajebackup;
    }
    
    public void setViajebackup(Viajebackup viajebackup) {
        this.viajebackup = viajebackup;
    }
    public String getLocalizadorCompraBackup() {
        return this.localizadorCompraBackup;
    }
    
    public void setLocalizadorCompraBackup(String localizadorCompraBackup) {
        this.localizadorCompraBackup = localizadorCompraBackup;
    }
    public Date getFechaCompraBackup() {
        return this.fechaCompraBackup;
    }
    
    public void setFechaCompraBackup(Date fechaCompraBackup) {
        this.fechaCompraBackup = fechaCompraBackup;
    }
    public double getImporteCompraBackup() {
        return this.importeCompraBackup;
    }
    
    public void setImporteCompraBackup(double importeCompraBackup) {
        this.importeCompraBackup = importeCompraBackup;
    }
    public Date getFechaBajaCompraBackup() {
        return this.fechaBajaCompraBackup;
    }
    
    public void setFechaBajaCompraBackup(Date fechaBajaCompraBackup) {
        this.fechaBajaCompraBackup = fechaBajaCompraBackup;
    }
    public Set getOcupacionbackups() {
        return this.ocupacionbackups;
    }
    
    public void setOcupacionbackups(Set ocupacionbackups) {
        this.ocupacionbackups = ocupacionbackups;
    }




}


