package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion  implements java.io.Serializable {


     private Integer idEstacion;
     private String nombre;
     private String direccion;
     private String localidad;
     private Set rutasForIdOrigen = new HashSet(0);
     private Set rutasForIdDestino = new HashSet(0);

    public Estacion() {
    }

	
    public Estacion(String nombre, String direccion, String localidad) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.localidad = localidad;
    }
    public Estacion(String nombre, String direccion, String localidad, Set rutasForIdOrigen, Set rutasForIdDestino) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.localidad = localidad;
       this.rutasForIdOrigen = rutasForIdOrigen;
       this.rutasForIdDestino = rutasForIdDestino;
    }
    public Estacion(Integer idEstacion, String nombre, String direccion, String localidad) {
        this.idEstacion= idEstacion;
        this.nombre = nombre;
        this.direccion = direccion;
        this.localidad = localidad;
    }
   
    public Integer getIdEstacion() {
        return this.idEstacion;
    }
    
    public void setIdEstacion(Integer idEstacion) {
        this.idEstacion = idEstacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public Set getRutasForIdOrigen() {
        return this.rutasForIdOrigen;
    }
    
    public void setRutasForIdOrigen(Set rutasForIdOrigen) {
        this.rutasForIdOrigen = rutasForIdOrigen;
    }
    public Set getRutasForIdDestino() {
        return this.rutasForIdDestino;
    }
    
    public void setRutasForIdDestino(Set rutasForIdDestino) {
        this.rutasForIdDestino = rutasForIdDestino;
    }




}


