package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private Ruta ruta;
     private Date horaSalida;
     private String tipoDia;
     private Set viajes = new HashSet(0);
     private Set viajebackups = new HashSet(0);

    public Horario() {
    }

	
    public Horario(Ruta ruta, Date horaSalida, String tipoDia) {
        this.ruta = ruta;
        this.horaSalida = horaSalida;
        this.tipoDia = tipoDia;
    }
    public Horario(Ruta ruta, Date horaSalida, String tipoDia, Set viajes, Set viajebackups) {
       this.ruta = ruta;
       this.horaSalida = horaSalida;
       this.tipoDia = tipoDia;
       this.viajes = viajes;
       this.viajebackups = viajebackups;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public String getTipoDia() {
        return this.tipoDia;
    }
    
    public void setTipoDia(String tipoDia) {
        this.tipoDia = tipoDia;
    }
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }
    public Set getViajebackups() {
        return this.viajebackups;
    }
    
    public void setViajebackups(Set viajebackups) {
        this.viajebackups = viajebackups;
    }




}


