package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ocupacionbackup generated by hbm2java
 */
public class Ocupacionbackup  implements java.io.Serializable {


     private Integer idOcupacionBackup;
     private Comprabackup comprabackup;
     private Viajerobackup viajerobackup;
     private int asientoBackup;
     private double importeBackup;
     private Date fechaBajaOcupacionBackup;

    public Ocupacionbackup() {
    }

    public Ocupacionbackup(Comprabackup comprabackup, Viajerobackup viajerobackup, int asientoBackup, double importeBackup, Date fechaBajaOcupacionBackup) {
       this.comprabackup = comprabackup;
       this.viajerobackup = viajerobackup;
       this.asientoBackup = asientoBackup;
       this.importeBackup = importeBackup;
       this.fechaBajaOcupacionBackup = fechaBajaOcupacionBackup;
    }
   
    public Integer getIdOcupacionBackup() {
        return this.idOcupacionBackup;
    }
    
    public void setIdOcupacionBackup(Integer idOcupacionBackup) {
        this.idOcupacionBackup = idOcupacionBackup;
    }
    public Comprabackup getComprabackup() {
        return this.comprabackup;
    }
    
    public void setComprabackup(Comprabackup comprabackup) {
        this.comprabackup = comprabackup;
    }
    public Viajerobackup getViajerobackup() {
        return this.viajerobackup;
    }
    
    public void setViajerobackup(Viajerobackup viajerobackup) {
        this.viajerobackup = viajerobackup;
    }
    public int getAsientoBackup() {
        return this.asientoBackup;
    }
    
    public void setAsientoBackup(int asientoBackup) {
        this.asientoBackup = asientoBackup;
    }
    public double getImporteBackup() {
        return this.importeBackup;
    }
    
    public void setImporteBackup(double importeBackup) {
        this.importeBackup = importeBackup;
    }
    public Date getFechaBajaOcupacionBackup() {
        return this.fechaBajaOcupacionBackup;
    }
    
    public void setFechaBajaOcupacionBackup(Date fechaBajaOcupacionBackup) {
        this.fechaBajaOcupacionBackup = fechaBajaOcupacionBackup;
    }




}


