package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private Integer idRuta;
     private Estacion estacionByIdOrigen;
     private Estacion estacionByIdDestino;
     private Date duracion;
     private double distancia;
     private double precio;
     private String comentario;
     private Set horarios = new HashSet(0);

    public Ruta() {
    }

	
    public Ruta(Estacion estacionByIdOrigen, Estacion estacionByIdDestino, Date duracion, double distancia, double precio, String comentario) {
        this.estacionByIdOrigen = estacionByIdOrigen;
        this.estacionByIdDestino = estacionByIdDestino;
        this.duracion = duracion;
        this.distancia = distancia;
        this.precio = precio;
        this.comentario = comentario;
    }
    public Ruta(Estacion estacionByIdOrigen, Estacion estacionByIdDestino, Date duracion, double distancia, double precio, String comentario, Set horarios) {
       this.estacionByIdOrigen = estacionByIdOrigen;
       this.estacionByIdDestino = estacionByIdDestino;
       this.duracion = duracion;
       this.distancia = distancia;
       this.precio = precio;
       this.comentario = comentario;
       this.horarios = horarios;
    }
   
    public Integer getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(Integer idRuta) {
        this.idRuta = idRuta;
    }
    public Estacion getEstacionByIdOrigen() {
        return this.estacionByIdOrigen;
    }
    
    public void setEstacionByIdOrigen(Estacion estacionByIdOrigen) {
        this.estacionByIdOrigen = estacionByIdOrigen;
    }
    public Estacion getEstacionByIdDestino() {
        return this.estacionByIdDestino;
    }
    
    public void setEstacionByIdDestino(Estacion estacionByIdDestino) {
        this.estacionByIdDestino = estacionByIdDestino;
    }
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }
    public double getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(double distancia) {
        this.distancia = distancia;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


