package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer idTarjeta;
     private Cliente cliente;
     private byte[] numeroTarjeta;
     private String tipoTarjeta;
     private int caducidadMes;
     private int caducidadAno;
     private Set compras = new HashSet(0);
     private Set comprabackups = new HashSet(0);

    public Tarjeta() {
    }

	
    public Tarjeta(Cliente cliente, byte[] numeroTarjeta, String tipoTarjeta, int caducidadMes, int caducidadAno) {
        this.cliente = cliente;
        this.numeroTarjeta = numeroTarjeta;
        this.tipoTarjeta = tipoTarjeta;
        this.caducidadMes = caducidadMes;
        this.caducidadAno = caducidadAno;
    }
    public Tarjeta(Cliente cliente, byte[] numeroTarjeta, String tipoTarjeta, int caducidadMes, int caducidadAno, Set compras, Set comprabackups) {
       this.cliente = cliente;
       this.numeroTarjeta = numeroTarjeta;
       this.tipoTarjeta = tipoTarjeta;
       this.caducidadMes = caducidadMes;
       this.caducidadAno = caducidadAno;
       this.compras = compras;
       this.comprabackups = comprabackups;
    }
   
    public Integer getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(Integer idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public byte[] getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(byte[] numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
    public String getTipoTarjeta() {
        return this.tipoTarjeta;
    }
    
    public void setTipoTarjeta(String tipoTarjeta) {
        this.tipoTarjeta = tipoTarjeta;
    }
    public int getCaducidadMes() {
        return this.caducidadMes;
    }
    
    public void setCaducidadMes(int caducidadMes) {
        this.caducidadMes = caducidadMes;
    }
    public int getCaducidadAno() {
        return this.caducidadAno;
    }
    
    public void setCaducidadAno(int caducidadAno) {
        this.caducidadAno = caducidadAno;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getComprabackups() {
        return this.comprabackups;
    }
    
    public void setComprabackups(Set comprabackups) {
        this.comprabackups = comprabackups;
    }




}


