package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Viajero generated by hbm2java
 */
public class Viajero  implements java.io.Serializable {


     private Integer idViajero;
     private String nifViajero;
     private String nombreViajero;
     private String apellidosViajero;
     private Set ocupacions = new HashSet(0);

    public Viajero() {
    }

	
    public Viajero(String nifViajero, String nombreViajero, String apellidosViajero) {
        this.nifViajero = nifViajero;
        this.nombreViajero = nombreViajero;
        this.apellidosViajero = apellidosViajero;
    }
    public Viajero(String nifViajero, String nombreViajero, String apellidosViajero, Set ocupacions) {
       this.nifViajero = nifViajero;
       this.nombreViajero = nombreViajero;
       this.apellidosViajero = apellidosViajero;
       this.ocupacions = ocupacions;
    }
   
    public Integer getIdViajero() {
        return this.idViajero;
    }
    
    public void setIdViajero(Integer idViajero) {
        this.idViajero = idViajero;
    }
    public String getNifViajero() {
        return this.nifViajero;
    }
    
    public void setNifViajero(String nifViajero) {
        this.nifViajero = nifViajero;
    }
    public String getNombreViajero() {
        return this.nombreViajero;
    }
    
    public void setNombreViajero(String nombreViajero) {
        this.nombreViajero = nombreViajero;
    }
    public String getApellidosViajero() {
        return this.apellidosViajero;
    }
    
    public void setApellidosViajero(String apellidosViajero) {
        this.apellidosViajero = apellidosViajero;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }




}


