package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private Integer idViaje;
     private Horario horario;
     private Date fecha;
     private int plazasLibres;
     private Set compras = new HashSet(0);

    public Viaje() {
    }

	
    public Viaje(Horario horario, Date fecha, int plazasLibres) {
        this.horario = horario;
        this.fecha = fecha;
        this.plazasLibres = plazasLibres;
    }
    public Viaje(Horario horario, Date fecha, int plazasLibres, Set compras) {
       this.horario = horario;
       this.fecha = fecha;
       this.plazasLibres = plazasLibres;
       this.compras = compras;
    }
   
    public Integer getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(Integer idViaje) {
        this.idViaje = idViaje;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getPlazasLibres() {
        return this.plazasLibres;
    }
    
    public void setPlazasLibres(int plazasLibres) {
        this.plazasLibres = plazasLibres;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


