package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viajerobackup generated by hbm2java
 */
public class Viajerobackup  implements java.io.Serializable {


     private Integer idViajeroBackup;
     private String nifViajeroBackup;
     private String nombreViajeroBackup;
     private String apellidosViajeroBackup;
     private Date fechaBajaViajeroBackup;
     private Set ocupacionbackups = new HashSet(0);

    public Viajerobackup() {
    }

	
    public Viajerobackup(String nifViajeroBackup, String nombreViajeroBackup, String apellidosViajeroBackup, Date fechaBajaViajeroBackup) {
        this.nifViajeroBackup = nifViajeroBackup;
        this.nombreViajeroBackup = nombreViajeroBackup;
        this.apellidosViajeroBackup = apellidosViajeroBackup;
        this.fechaBajaViajeroBackup = fechaBajaViajeroBackup;
    }
    public Viajerobackup(String nifViajeroBackup, String nombreViajeroBackup, String apellidosViajeroBackup, Date fechaBajaViajeroBackup, Set ocupacionbackups) {
       this.nifViajeroBackup = nifViajeroBackup;
       this.nombreViajeroBackup = nombreViajeroBackup;
       this.apellidosViajeroBackup = apellidosViajeroBackup;
       this.fechaBajaViajeroBackup = fechaBajaViajeroBackup;
       this.ocupacionbackups = ocupacionbackups;
    }
   
    public Integer getIdViajeroBackup() {
        return this.idViajeroBackup;
    }
    
    public void setIdViajeroBackup(Integer idViajeroBackup) {
        this.idViajeroBackup = idViajeroBackup;
    }
    public String getNifViajeroBackup() {
        return this.nifViajeroBackup;
    }
    
    public void setNifViajeroBackup(String nifViajeroBackup) {
        this.nifViajeroBackup = nifViajeroBackup;
    }
    public String getNombreViajeroBackup() {
        return this.nombreViajeroBackup;
    }
    
    public void setNombreViajeroBackup(String nombreViajeroBackup) {
        this.nombreViajeroBackup = nombreViajeroBackup;
    }
    public String getApellidosViajeroBackup() {
        return this.apellidosViajeroBackup;
    }
    
    public void setApellidosViajeroBackup(String apellidosViajeroBackup) {
        this.apellidosViajeroBackup = apellidosViajeroBackup;
    }
    public Date getFechaBajaViajeroBackup() {
        return this.fechaBajaViajeroBackup;
    }
    
    public void setFechaBajaViajeroBackup(Date fechaBajaViajeroBackup) {
        this.fechaBajaViajeroBackup = fechaBajaViajeroBackup;
    }
    public Set getOcupacionbackups() {
        return this.ocupacionbackups;
    }
    
    public void setOcupacionbackups(Set ocupacionbackups) {
        this.ocupacionbackups = ocupacionbackups;
    }




}


