package POJOS;
// Generated 01-mar-2020 10:27:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viajebackup generated by hbm2java
 */
public class Viajebackup  implements java.io.Serializable {


     private Integer idViajeBackup;
     private Horario horario;
     private Date fechaBackup;
     private int plazasLibresBackup;
     private Date fechaBajaViajeBackup;
     private Set comprabackups = new HashSet(0);

    public Viajebackup() {
    }

	
    public Viajebackup(Horario horario, Date fechaBackup, int plazasLibresBackup, Date fechaBajaViajeBackup) {
        this.horario = horario;
        this.fechaBackup = fechaBackup;
        this.plazasLibresBackup = plazasLibresBackup;
        this.fechaBajaViajeBackup = fechaBajaViajeBackup;
    }
    public Viajebackup(Horario horario, Date fechaBackup, int plazasLibresBackup, Date fechaBajaViajeBackup, Set comprabackups) {
       this.horario = horario;
       this.fechaBackup = fechaBackup;
       this.plazasLibresBackup = plazasLibresBackup;
       this.fechaBajaViajeBackup = fechaBajaViajeBackup;
       this.comprabackups = comprabackups;
    }
   
    public Integer getIdViajeBackup() {
        return this.idViajeBackup;
    }
    
    public void setIdViajeBackup(Integer idViajeBackup) {
        this.idViajeBackup = idViajeBackup;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFechaBackup() {
        return this.fechaBackup;
    }
    
    public void setFechaBackup(Date fechaBackup) {
        this.fechaBackup = fechaBackup;
    }
    public int getPlazasLibresBackup() {
        return this.plazasLibresBackup;
    }
    
    public void setPlazasLibresBackup(int plazasLibresBackup) {
        this.plazasLibresBackup = plazasLibresBackup;
    }
    public Date getFechaBajaViajeBackup() {
        return this.fechaBajaViajeBackup;
    }
    
    public void setFechaBajaViajeBackup(Date fechaBajaViajeBackup) {
        this.fechaBajaViajeBackup = fechaBajaViajeBackup;
    }
    public Set getComprabackups() {
        return this.comprabackups;
    }
    
    public void setComprabackups(Set comprabackups) {
        this.comprabackups = comprabackups;
    }




}


